Repository oban-bg/oban, pull requests merged in 2021-02, with the labels that each got.

#410 Support Oban.insert_all/4 with a changes function
  lib/oban.ex
  lib/oban/job.ex
  lib/oban/query.ex
  lib/oban/worker.ex
  test/integration/inserting_test.exs
Labels: enhancement

#434 Provide repeater plugin as notification workaround
  guides/troubleshooting.md
  lib/oban/plugins/repeater.ex
  mix.exs
  test/oban/plugins/cron_test.exs
  test/oban/plugins/pruner_test.exs
  test/oban/plugins/repeater_test.exs
  test/oban/plugins/stager_test.exs
  test/support/plugin_telemetry_handler.ex
Labels: area:oss, kind:feature

#438 Upgrade minimum Elixir version to 1.9
  .github/workflows/ci.yml
  README.md
  mix.exs
  test/test_helper.exs
Labels: area:oss, kind:chore
